/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceChatRouteImport } from './routes/voice-chat'
import { Route as TextChatRouteImport } from './routes/text-chat'
import { Route as IndexRouteImport } from './routes/index'

const VoiceChatRoute = VoiceChatRouteImport.update({
  id: '/voice-chat',
  path: '/voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TextChatRoute = TextChatRouteImport.update({
  id: '/text-chat',
  path: '/text-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/text-chat': typeof TextChatRoute
  '/voice-chat': typeof VoiceChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/text-chat': typeof TextChatRoute
  '/voice-chat': typeof VoiceChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/text-chat': typeof TextChatRoute
  '/voice-chat': typeof VoiceChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/text-chat' | '/voice-chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/text-chat' | '/voice-chat'
  id: '__root__' | '/' | '/text-chat' | '/voice-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextChatRoute: typeof TextChatRoute
  VoiceChatRoute: typeof VoiceChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-chat': {
      id: '/voice-chat'
      path: '/voice-chat'
      fullPath: '/voice-chat'
      preLoaderRoute: typeof VoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-chat': {
      id: '/text-chat'
      path: '/text-chat'
      fullPath: '/text-chat'
      preLoaderRoute: typeof TextChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextChatRoute: TextChatRoute,
  VoiceChatRoute: VoiceChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
